# Generated by Django 5.2.6 on 2025-09-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessedPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_id",
                    models.CharField(
                        help_text="O ID único do post do Reddit (ex: '1ab2cd')",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "text_hash",
                    models.CharField(
                        db_index=True,
                        help_text="Hash SHA-256 do conteúdo do texto para evitar duplicados",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="O título do post processado", max_length=300
                    ),
                ),
                (
                    "video_path",
                    models.CharField(
                        blank=True,
                        help_text="O caminho para o ficheiro de vídeo final gerado",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
